### PR TITLE
Convert snippets to ES6 syntax

### PR DESCRIPTION
**Pull request by mileszs**
Also dropped semicolons

I don't know that you have any interest in having an ES6 branch, but I thought I'd send a pull request for your perusal. Thanks for the plugin!

### CODE REVIEW

**Comment by justinj** [comment]
Sweet. I've actually noticed a number of people fork and add ES6 snippets, so maybe instead of a branch there should be a completely separate repo? It seems like everyone is moving to ES6 for React pretty fast, so it might be better if it's easily available.

If you want to keep a fork (or new repo) for these I'd be happy to link to them in the readme here (also happy to keep a branch here if you'd prefer).

**Comment by mileszs** [comment]
Ah, cool. I could do that. I didn't want to step on your toes. :-)

Miles Z. Sterrett
http://getfretless.com
p: 317.475.0993 x1

**Comment by mileszs** [comment]
(Ugh, sorry about business-time email sig sneaking in there.)

**Comment by pgilad** [comment]
Any news on this? Should we use a specific fork?

**Comment by justinj** [comment]
@pgilad I'm not familiar with an ES6 version to use :( if you (or anyone else) can recommend one I will link to it in the README.

**Comment by mileszs** [comment]
I have not used this in several years. Closing to remove it from my list of responsibilities in GitHub. :-)

**Pull request closed without merging**
